(() => {
  'use strict';
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const quizData = [
    {id:'python',topic:'Python',title:'Python foundations',desc:'Variables, loops & the little things that click.',level:'Beginner',time:8,questions:[{q:'What does print(3 ** 2) display?',o:['6','9','8','32'],a:1},{q:'Which value represents no value in Python?',o:['undefined','nil','None','void'],a:2},{q:'What is the result of len("hello")?',o:['4','5','6','hello'],a:1},{q:'Which one creates a list?',o:['(1, 2)','{1, 2}','[1, 2]','<1, 2>'],a:2}]},
    {id:'java',topic:'Java',title:'Java, one step at a time',desc:'Objects, types & the building blocks of Java.',level:'Beginner',time:10,questions:[{q:'Which keyword creates a new object in Java?',o:['make','new','create','object'],a:1},{q:'Which is the entry-point method in a Java application?',o:['start()','run()','main()','init()'],a:2},{q:'Which type stores true or false?',o:['Boolean','bool','boolean','bit'],a:2},{q:'What does a class describe?',o:['A blueprint for objects','A loop','A package manager','A compiler'],a:0}]},
    {id:'sql',topic:'SQL',title:'SQL for the curious',desc:'Ask your database better questions.',level:'Beginner',time:7,questions:[{q:'Which clause filters rows in a query?',o:['ORDER BY','WHERE','GROUP BY','SELECT'],a:1},{q:'Which command retrieves data from a table?',o:['GET','OPEN','SELECT','FETCH ALL'],a:2},{q:'How do you sort results in descending order?',o:['SORT DESC','ORDER DESC','ORDER BY ... DESC','GROUP BY DESC'],a:2},{q:'Which function counts rows?',o:['SUM()','TOTAL()','COUNT()','ROWS()'],a:2}]},
    {id:'cpp',topic:'C++',title:'C++: the first steps',desc:'Pointers, values & a little more confidence.',level:'Intermediate',time:12,questions:[{q:'Which symbol ends most C++ statements?',o:['.',':',';','!'],a:2},{q:'Which header provides std::cout?',o:['<input>','<iostream>','<console>','<stdio>'],a:1},{q:'What does & mean in a type declaration?',o:['Pointer','Reference','Array','Template'],a:1},{q:'Which keyword allocates on the free store?',o:['alloc','malloc','new','create'],a:2}]},
    {id:'dotnet',topic:'.NET',title:'.NET, demystified',desc:'Get to know the platform behind the apps.',level:'Beginner',time:9,questions:[{q:'Which language is commonly used with .NET?',o:['C#','Ruby','Swift','PHP'],a:0},{q:'What does CLR stand for?',o:['Common Language Runtime','Code Linking Resource','Core Library Registry','Common Logic Reference'],a:0},{q:'Which command creates a new .NET project?',o:['dotnet make','dotnet new','dotnet init','dotnet create'],a:1},{q:'What is NuGet?',o:['A database','A package manager','A compiler','A text editor'],a:1}]}
  ];
  const upcoming = [
    {topic:'Python',title:'Python quick check',date:'Oct 14',time:'10:00 AM',id:'python'},
    {topic:'SQL',title:'SQL select & sort',date:'Oct 16',time:'2:30 PM',id:'sql'},
    {topic:'Java',title:'Java essentials',date:'Oct 18',time:'11:00 AM',id:'java'}
  ];
  const firebaseReady = !!(window.QUIZLOOM_FIREBASE_CONFIG?.apiKey && window.QUIZLOOM_FIREBASE_CONFIG?.projectId);
  let auth=null, db=null, currentUser=null, currentRole='student', authMode='login', activeQuiz=null, questionIndex=0, answers=[], quizTimer=null, timerLeft=0;
  const modal = id => bootstrap.Modal.getOrCreateInstance(document.getElementById(id));
  const toast = msg => {const el=document.createElement('div');el.className='app-toast';el.textContent=msg;$('#toastRegion').append(el);setTimeout(()=>el.remove(),3500)};
  const key = (s='') => s.toLowerCase().replace(/[^a-z0-9]+/g,'-');
  const cards = list => list.map(q=>`<article class="quiz-card-item" data-id="${q.id}" tabindex="0" role="button" aria-label="Open ${q.title}"><div class="topic-art topic-${key(q.topic==='C++'?'cpp':q.topic==='.NET'?'dotnet':q.topic)}"><span class="topic-tag">${q.level||'Beginner'}</span><span class="topic-icon">${q.topic==='Python'?'Py':q.topic==='Java'?'J':q.topic==='SQL'?'⌘':q.topic==='C++'?'C+':'.N'}</span></div><h3>${escapeHtml(q.title)}</h3><p>${escapeHtml(q.desc||'A new quiz, made for your learning journey.')}</p><div class="card-meta"><span>◷ ${q.time||8} min</span><span class="level">${q.questions?.length||4} questions</span></div></article>`).join('');
  function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function renderCards(filter='All') {let list=quizData.filter(q=>filter==='All'||q.topic===filter);$('#quizGrid').innerHTML=list.length?cards(list):'<div class="empty-state">No quizzes in this topic yet. Check back soon!</div>'; $$('.quiz-card-item').forEach(el=>{el.addEventListener('click',()=>openQuiz(el.dataset.id));el.addEventListener('keydown',e=>{if(e.key==='Enter')openQuiz(el.dataset.id)})});if(currentRole==='admin')$$('.quiz-card-item').forEach(el=>{const button=document.createElement('button');button.className='btn btn-sm btn-outline-secondary rounded-pill mt-2 w-100';button.textContent='Manage quiz';button.onclick=e=>{e.stopPropagation();manageQuiz(el.dataset.id)};el.append(button)})}
  function hydrate(){renderCards();const notice=localStorage.getItem('quizloom-notice')||'true';if(notice==='true')$('#notificationBtn').classList.add('has-notice')}
  function setUser(user,role,name){const prior=currentRole;currentUser=user;currentRole=role||'student';if(user){$('#loginBtn').classList.add('d-none');$('#signupBtn').classList.add('d-none');$('#userMenu').classList.remove('d-none');$('#userMenu').style.display='flex';$('#avatarBtn').textContent=(name||user.displayName||user.email||'Q').slice(0,1).toUpperCase();$('.brand').setAttribute('data-role',currentRole);if(currentRole==='admin'){setupAdmin();if(prior!==currentRole)toast(`Welcome, ${name||'admin'} — admin tools are ready.`)}else if(prior!==currentRole)toast(`Welcome back${name?', '+name:''}! Your quiz calendar is ready.`)}else{$('#loginBtn').classList.remove('d-none');$('#signupBtn').classList.remove('d-none');$('#userMenu').classList.add('d-none');$('.brand').removeAttribute('data-role');$('#adminCreateBtn')?.remove();renderCards($('#filters .selected')?.dataset.filter||'All')} }
  function openAuth(mode){authMode=mode;$('#authTitle').textContent=mode==='signup'?'Find your rhythm.':'Good to see you.';$('#authSubtitle').textContent=mode==='signup'?'A free account is your first small win.':'Pick up right where you left off.';$('#authEyebrow').textContent=mode==='signup'?'YOUR NEXT CHAPTER':'WELCOME BACK';$('#nameField').hidden=mode!=='signup';$('#authPassword').autocomplete=mode==='signup'?'new-password':'current-password';$('#authSubmit').innerHTML=mode==='signup'?'Create account <span>↗</span>':'Sign in <span>↗</span>';$('#authToggle').innerHTML=mode==='signup'?'Already have an account? <button>Sign in</button>':'New to Quizloom? <button>Make an account</button>';$('#authToggle button').onclick=()=>openAuth(authMode==='signup'?'login':'signup');$('#demoNote').textContent=firebaseReady?'Firebase connected · your account is securely stored':'Demo mode · create any email and password to explore';modal('authModal').show()}
  $$('.role-switch button').forEach(btn=>btn.onclick=()=>{$$('.role-switch button').forEach(b=>b.classList.toggle('active',b===btn));currentRole=btn.dataset.role;$('#authHint').textContent=currentRole==='admin'?'Admin access is limited to accounts with the admin role.':'Your role is saved securely with your account.'});
  async function authSubmit(e){e.preventDefault();const email=$('#authEmail').value.trim().toLowerCase(),password=$('#authPassword').value,name=$('#authName').value.trim();const submit=$('#authSubmit');submit.disabled=true;try{let user,role=currentRole,displayName=name;if(firebaseReady){if(authMode==='signup'){const cred=await auth.createUserWithEmailAndPassword(email,password);user=cred.user;if(name)await user.updateProfile({displayName:name});await db.collection('users').doc(user.uid).set({email,displayName:name,role,createdAt:firebase.firestore.FieldValue.serverTimestamp()});}else{const cred=await auth.signInWithEmailAndPassword(email,password);user=cred.user;const doc=await db.collection('users').doc(user.uid).get();if(!doc.exists)throw new Error('This account has no Quizloom profile yet. Please sign up first.');role=doc.data().role;displayName=doc.data().displayName;if(role!==currentRole){await auth.signOut();throw new Error(`This is a ${role} account. Choose the ${role} sign-in tab.`)}}sessionStorage.setItem('quizloomRole',role);sessionStorage.setItem('quizloomName',displayName||'');setUser(user,role,displayName);await loadRemoteQuizzes();}else{const accounts=JSON.parse(localStorage.getItem('quizloom-accounts')||'{}');if(authMode==='signup'){if(accounts[email])throw new Error('An account already exists with this email. Please sign in.');accounts[email]={password,name,role};localStorage.setItem('quizloom-accounts',JSON.stringify(accounts));}else{const account=accounts[email];if(!account)throw new Error('No account found for this email. Choose Make an account to register.');if(account.password!==password||account.role!==currentRole)throw new Error(account.role!==currentRole?`This is a ${account.role} account. Choose the ${account.role} sign-in tab.`:'That password does not match this account.');displayName=account.name;role=account.role;}user={uid:key(email),email,displayName};sessionStorage.setItem('quizloomRole',role);sessionStorage.setItem('quizloomName',displayName);setUser(user,role,displayName)}modal('authModal').hide();}catch(err){toast(err.message||'Could not sign in. Please try again.')}finally{submit.disabled=false}}
  async function loadRemoteQuizzes(){if(!firebaseReady)return;try{const snap=await db.collection('quizzes').where('published','==',true).get();snap.forEach(d=>{const data=d.data();if(data.topic&&Array.isArray(data.questions)&&!quizData.some(q=>q.id===d.id))quizData.push({id:d.id,...data})});renderCards($('#filters .selected')?.dataset.filter||'All')}catch(e){console.warn('Could not load quizzes',e)}}
  async function openQuiz(id){if(!currentUser){openAuth('login');toast('Sign in to start your learning session.');return}if(currentRole==='admin'){toast('Student accounts attend quizzes. Switch to a student account to begin.');return}const q=quizData.find(x=>x.id===id);if(!q)return;activeQuiz=q;questionIndex=0;answers=Array(q.questions.length).fill(null);const attempted=JSON.parse(localStorage.getItem('quizloom-attempts')||'{}');if(attempted[`${currentUser.uid}_${q.id}`]){toast('You have already completed this quiz. Multiple attempts are not allowed.');return}if(firebaseReady){const attemptRef=db.collection('attempts').doc(`${currentUser.uid}_${q.id}`);const prior=await attemptRef.get();if(prior.exists){toast('You have already completed this quiz. Multiple attempts are not allowed.');return}const lockRef=db.collection('activeAttempts').doc(`${currentUser.uid}_${q.id}`);try{await db.runTransaction(async tx=>{const d=await tx.get(lockRef);if(d.exists&&d.data().expiresAt?.toMillis()>Date.now())throw new Error('This student already has an active quiz session. Multiple attempts are not allowed.');tx.set(lockRef,{uid:currentUser.uid,quizId:q.id,expiresAt:firebase.firestore.Timestamp.fromMillis(Date.now()+30*60*1000),startedAt:firebase.firestore.FieldValue.serverTimestamp()})})}catch(e){toast(e.message||'An active attempt is already in progress.');return}}$('#quizTitle').textContent=q.title;$('#quizTopicLabel').textContent=`${q.topic.toUpperCase()} · QUICK CHECK`;renderQuestion();modal('quizModal').show();timerLeft=(q.time||8)*60;clearInterval(quizTimer);quizTimer=setInterval(()=>{timerLeft--;if(timerLeft<=0){clearInterval(quizTimer);submitQuiz()}},1000)}
  function renderQuestion(){const q=activeQuiz.questions[questionIndex],pct=(questionIndex/activeQuiz.questions.length)*100;$('#quizBody').innerHTML=`<div class="question-progress"><i style="width:${pct}%"></i></div><div class="question-count">QUESTION ${questionIndex+1} OF ${activeQuiz.questions.length} <span style="float:right">${Math.floor(timerLeft/60)}:${String(timerLeft%60).padStart(2,'0')} left</span></div><div class="question-text">${escapeHtml(q.q)}</div><div class="answer-list">${q.o.map((o,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${i}" ${answers[questionIndex]===i?'checked':''}>${escapeHtml(o)}</label>`).join('')}</div><div class="quiz-controls"><button class="btn btn-outline-secondary rounded-pill" id="prevQuestion" ${questionIndex===0?'disabled':''}>← Previous</button><button class="btn btn-dark rounded-pill" id="nextQuestion">${questionIndex===activeQuiz.questions.length-1?'Finish quiz':'Next question →'}</button></div>`;$$('input[name="answer"]').forEach(x=>x.onchange=()=>answers[questionIndex]=Number(x.value));$('#prevQuestion').onclick=()=>{if(questionIndex>0){questionIndex--;renderQuestion()}};$('#nextQuestion').onclick=()=>{if(answers[questionIndex]===null){toast('Choose an answer before continuing.');return}if(questionIndex<activeQuiz.questions.length-1){questionIndex++;renderQuestion()}else submitQuiz()}}
  async function submitQuiz(){clearInterval(quizTimer);const correct=answers.reduce((n,a,i)=>n+(a===activeQuiz.questions[i].a?1:0),0),score=Math.round(correct/activeQuiz.questions.length*100),attemptKey=`${currentUser.uid}_${activeQuiz.id}`;const attempts=JSON.parse(localStorage.getItem('quizloom-attempts')||'{}');attempts[attemptKey]={score,at:Date.now()};localStorage.setItem('quizloom-attempts',JSON.stringify(attempts));if(firebaseReady){try{await db.collection('attempts').doc(attemptKey).set({uid:currentUser.uid,quizId:activeQuiz.id,score,correct,total:activeQuiz.questions.length,answers,submittedAt:firebase.firestore.FieldValue.serverTimestamp()});await db.collection('activeAttempts').doc(attemptKey).delete()}catch(e){toast('Your result is saved locally, but Firebase sync failed.');console.error(e)}}$('#quizBody').innerHTML=`<div class="result-panel"><div class="score-ring" style="--score:${score*3.6}deg"><span>${score}%</span></div><h3>${score>=75?'Look at you go!':score>=50?'Nice work, keep going.':'Every try teaches you something.'}</h3><p>You got <b>${correct} of ${activeQuiz.questions.length}</b> right in ${escapeHtml(activeQuiz.title)}.</p><button class="btn btn-dark rounded-pill px-4" id="resultDone">Back to my quizzes ↗</button></div>`;$('#resultDone').onclick=()=>{modal('quizModal').hide();toast('Result saved. This quiz is now marked complete.')}}
  function showNotifications(){const read=JSON.parse(localStorage.getItem('quizloom-read-notices')||'{}');$('#notificationList').innerHTML=upcoming.map(n=>`<div class="notification-item"><i class="mini-dot" style="${read[n.id]?'background:#d8d8d3':''}"></i><div><b>${escapeHtml(n.title)} · ${n.topic}</b><span>${n.date} · ${n.time} · ${read[n.id]?'Reminder seen':'Coming up soon'}</span></div></div>`).join('');localStorage.setItem('quizloom-notice','false');modal('notifyModal').show()}
  function setupAdmin(){if(currentRole!=='admin'||!currentUser)return;const heading=$('.section-heading>div');if(heading&&!$('#adminCreateBtn')){const b=document.createElement('button');b.id='adminCreateBtn';b.className='btn btn-dark rounded-pill btn-sm mt-3';b.textContent='+ Create a quiz';b.onclick=createQuiz;heading.append(b)}renderCards($('#filters .selected')?.dataset.filter||'All')}
  async function createQuiz(){const topic=prompt('Quiz topic (Python, Java, SQL, C++, .NET):','Python');if(!topic)return;if(!['python','java','sql','c++','.net'].includes(topic.toLowerCase())){toast('Choose Python, Java, SQL, C++, or .NET.');return}const title=prompt('Quiz title:');if(!title)return;const question=prompt('First question:');if(!question)return;const optionText=prompt('Enter four options separated by |','Option A|Option B|Option C|Option D');if(!optionText)return;const options=optionText.split('|').map(x=>x.trim());if(options.length!==4){toast('Please provide exactly four options, separated by |.');return}const answer=Number(prompt('Which option is correct? Enter 1, 2, 3 or 4.','1'))-1;if(answer<0||answer>3||Number.isNaN(answer)){toast('Answer must be 1, 2, 3 or 4.');return}const newQ={id:`custom-${Date.now()}`,topic:topic.toUpperCase()==='C++'?'C++':topic.toUpperCase()==='.NET'?'.NET':topic[0].toUpperCase()+topic.slice(1).toLowerCase(),title,desc:'A fresh quiz created by your admin.',level:'Beginner',time:5,questions:[{q:question,o:options,a:answer}],published:true};quizData.unshift(newQ);if(firebaseReady){try{await db.collection('quizzes').doc(newQ.id).set({...newQ,createdBy:currentUser.uid,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){toast('Quiz is available locally; Firebase save failed.')}}renderCards($('#filters .selected')?.dataset.filter||'All');toast('Quiz created and published!')}
  async function manageQuiz(id){const q=quizData.find(x=>x.id===id);if(!q)return;const action=prompt(`Manage “${q.title}”\n1 — Edit title\n2 — Delete quiz\n3 — Cancel`,'3');if(action==='1'){const title=prompt('New title:',q.title);if(!title)return;q.title=title;if(firebaseReady)await db.collection('quizzes').doc(id).update({title});renderCards($('#filters .selected')?.dataset.filter||'All');toast('Quiz updated.')}else if(action==='2'&&confirm(`Delete “${q.title}” from the quiz library?`)){quizData.splice(quizData.findIndex(x=>x.id===id),1);if(firebaseReady)await db.collection('quizzes').doc(id).delete();renderCards($('#filters .selected')?.dataset.filter||'All');toast('Quiz deleted.')}}
  function bind(){hydrate();$('#loginBtn').onclick=()=>openAuth('login');$('#signupBtn').onclick=()=>openAuth('signup');$('#ctaSignup').onclick=()=>openAuth('signup');$('#exploreBtn').onclick=()=>document.querySelector('#quizzes').scrollIntoView({behavior:'smooth'});$('#allQuizzes').onclick=e=>{e.preventDefault();$('#filters .selected').click();document.querySelector('#quizzes').scrollIntoView({behavior:'smooth'})};$('#howBtn').onclick=()=>toast('Choose a topic, take a short quiz, and build your streak. Your progress belongs to you.');$('#notificationBtn').onclick=showNotifications;$('#authForm').onsubmit=authSubmit;$('#mobileMenu').onclick=()=>document.body.classList.toggle('mobile-open');$$('.filter-pill').forEach(b=>b.onclick=()=>{$$('.filter-pill').forEach(x=>x.classList.toggle('selected',x===b));renderCards(b.dataset.filter)});$$('.main-nav a').forEach(a=>a.onclick=()=>{$$('.main-nav a').forEach(x=>x.classList.toggle('active',x===a));if(a.dataset.view==='quizzes')document.querySelector('#quizzes').scrollIntoView({behavior:'smooth'});else if(a.dataset.view==='about')document.querySelector('.bottom-cta').scrollIntoView({behavior:'smooth'});else window.scrollTo({top:0,behavior:'smooth'})});$('#logoutBtn').onclick=async()=>{clearInterval(quizTimer);if(firebaseReady)await auth.signOut();sessionStorage.removeItem('quizloomRole');sessionStorage.removeItem('quizloomName');setUser(null);toast('You’ve signed out. See you next time!')};}
  function init(){bind();if(firebaseReady){try{firebase.initializeApp(window.QUIZLOOM_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();auth.setPersistence(firebase.auth.Auth.Persistence.SESSION);auth.onAuthStateChanged(async user=>{if(user){const doc=await db.collection('users').doc(user.uid).get();const role=doc.exists?doc.data().role:sessionStorage.getItem('quizloomRole');if(!role){await auth.signOut();return}setUser(user,role,doc.data()?.displayName||user.displayName);await loadRemoteQuizzes()}else setUser(null)});}catch(e){console.error('Firebase initialization failed',e);toast('Firebase setup needs attention. Running in demo mode.')}}else{const role=sessionStorage.getItem('quizloomRole');if(role){const accounts=JSON.parse(localStorage.getItem('quizloom-accounts')||'{}');const email=Object.keys(accounts).find(k=>accounts[k].role===role);if(email)setUser({uid:key(email),email,displayName:sessionStorage.getItem('quizloomName')},role,sessionStorage.getItem('quizloomName'))}}}
  init();
})();
